services:
  postgres:
    image: postgres:18
    container_name: rehab-bd
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_SERVER}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rehab-web
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
