version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: rehab-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_SERVER}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rehab
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rehab-secure.rule=Host(`rehab.promotion-pal.ru`)"
      - "traefik.http.routers.rehab-secure.entrypoints=websecure"
      - "traefik.http.routers.rehab-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.rehab.loadbalancer.server.port=3000"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
    name: traefik-network
